<?php
return [
    "categories"=>[
        1=>[
            "name"=>"艺术家.成果",
            "slug"=>"艺术家.成果",
            "parent"=>0,
            "children"=>[
                11=>[
                    "name"=>"爱心产品",
                    "slug"=>"爱心产品",
                    "parent"=>1
                ],
                12=>[
                    "name"=>"学生作品",
                    "slug"=>"学生作品",
                    "parent"=>1
                ]
            ]
        ],
        2=>[
            "name"=>"艺术家.动态",
            "slug"=>"艺术家.动态",
            "parent"=>0
        ],
        3=>[
            "name"=>"文化项目清单",
            "slug"=>"文化项目清单",
            "parent"=>0
        ],
        4=>[
            "name"=>"快乐美术教室捐赠",
            "slug"=>"快乐美术教室捐赠",
            "parent"=>0,
            "children"=>[
                13=>[
                    "name"=>"捐赠名单",
                    "slug"=>"捐赠名单",
                    "parent"=>4
                ],
                14=>[
                    "name"=>"活动感言",
                    "slug"=>"活动感言",
                    "parent"=>4
                ],
                15=>[
                    "name"=>"历年活动",
                    "slug"=>"历年活动",
                    "parent"=>4
                ]
            ]
        ],
        5=>[
            "name"=>"志愿者活动",
            "slug"=>"志愿者活动",
            "parent"=>0,
            "children"=>[
                16=>[
                    "name"=>"志愿者感言",
                    "slug"=>"志愿者感言",
                    "parent"=>5
                ],
                17=>[
                    "name"=>"历年活动",
                    "slug"=>"历年活动",
                    "parent"=>5
                ]
            ]
        ],
        6=>[
            "name"=>"儿童画征集&产品开发",
            "slug"=>"儿童画征集&产品开发",
            "parent"=>0,
            "children"=>[
                18=>[
                    "name"=>"小学生感言",
                    "slug"=>"小学生感言",
                    "parent"=>6
                ],
                19=>[
                    "name"=>"以往作品",
                    "slug"=>"以往作品",
                    "parent"=>6
                ],
                20=>[
                    "name"=>"征集函",
                    "slug"=>"征集函",
                    "parent"=>6
                ]
            ]
        ],
        7=>[
            "name"=>"教师培训",
            "slug"=>"教师培训",
            "parent"=>0,
            "children"=>[
                21=>[
                    "name"=>"培训反馈",
                    "slug"=>"培训反馈",
                    "parent"=>7
                ],
                22=>[
                    "name"=>"历年活动",
                    "slug"=>"历年活动",
                    "parent"=>7
                ],
                25=>[
                    "name"=>"招募岗位",
                    "slug"=>"招募岗位",
                    "parent"=>7
                ]
            ]
        ],
        8=>[
            "name"=>"大学奖学金活动",
            "slug"=>"大学奖学金活动",
            "parent"=>0
        ],
        9=>[
            "name"=>"大学生感言",
            "slug"=>"大学生感言",
            "parent"=>0
        ],
        10=>[
            "name"=>"实习生",
            "slug"=>"实习生",
            "parent"=>0,
            "children"=>[
                23=>[
                    "name"=>"实习生风采",
                    "slug"=>"实习生风采",
                    "parent"=>10
                ],
                24=>[
                    "name"=>"招募岗位",
                    "slug"=>"招募岗位",
                    "parent"=>10
                ]
            ]
        ],
        25=>[
            "name"=>"视频",
            "slug"=>"视频",
            "parent"=>0
        ]
    ]
];
