<?php
return [
    "imageSizes"=>[
        "thumbnail"=>[
            [
                "suffix"=>"-320x",
                "handle"=>"imageMogr2/thumbnail/320x"
            ]
        ],
        "bgImage"=>[
            [
                "suffix"=>"-half",
                "handle"=>"imageMogr2/thumbnail/!50p"
            ]
        ]

    ],
    "perShowCount"=>[
        "default"=>10
    ],
    "categories"=>[
        "artHonor"=>1,
        "artNews"=>2,
        "room"=>3,
        "activityRoom"=>4,
        "donation"=>5,//捐赠名单
        "teacherTrain"=>6,
        "activityTeacherTrain"=>7,
        "speechTeacherTrain"=>8,
        "resultTeacherTrain"=>9,
        "volunteer"=>10,//志愿者活动
        "activityVolunteer"=>11,
        "speechVolunteer"=>12,
        "volunteerTrain"=>13,
        "childDraw"=>14,//儿童画
        "childDrawCollect"=>15,//儿童画征集
        "resultChildDraw"=>16,
        "videoChildDraw"=>17,//儿童画视频
        "award"=>18,//高校奖学金
        "resultCollegeStudent"=>19,
        "trainee"=>20,
        "speechTrainee"=>21,
        "recruit"=>22,//实习生招募
        "cultureProgram"=>23,//艺术传承
        "story"=>24,//人物故事
        "video"=>26,//视频
        "wechat"=>27

    ]
];
